name: conda-env
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.8 and later.
- python=3.8.18


- pip:
  - azureml-train-automl-runtime==1.54.0.post1
  - inference-schema
  - azureml-interpret==1.54.0
  - azureml-defaults==1.54.0
- numpy==1.22.4
- pandas==1.3.5
- scikit-learn==1.0.2
- py-xgboost==1.3.3
- prophet==1.1.4
- holidays==0.29
- psutil==5.9.3
- flask=2.2.5
- gunicorn=21.2.0
channels:
- anaconda
- conda-forge
